// <auto-generated />
using System;
using AutoSync.EFC;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoSync.EFC.Migrations
{
    [DbContext(typeof(AutoSyncDbContext))]
    partial class AutoSyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoSync.Core.Authorization.Roles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AuditDetailId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            RoleName = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2L,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 3L,
                            RoleName = "Supervisor"
                        },
                        new
                        {
                            Id = 4L,
                            RoleName = "Quality Checker"
                        },
                        new
                        {
                            Id = 5L,
                            RoleName = "Technician"
                        });
                });

            modelBuilder.Entity("AutoSync.Core.Authorization.Setting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AuditDetailId")
                        .HasColumnType("bigint");

                    b.Property<int?>("AutoDeleteInterval")
                        .HasColumnType("int");

                    b.Property<string>("AutoSyncDays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AutoSyncTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FolderFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SupervisorId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Setting");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AutoDeleteInterval = 15,
                            AutoSyncDays = "Sunday,Monday,Tuesday",
                            AutoSyncTime = "17:30",
                            FolderFilePath = "D:\\Kishore\\PrimeMover",
                            SupervisorId = 2L,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 2L,
                            AutoDeleteInterval = 15,
                            AutoSyncDays = "Sunday,Monday,Tuesday",
                            AutoSyncTime = "17:30",
                            FolderFilePath = "D:\\Satheesh\\PrimeMover",
                            SupervisorId = 2L,
                            UserId = 4L
                        });
                });

            modelBuilder.Entity("AutoSync.Core.Authorization.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AuditDetailId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsActive = true,
                            Password = "superadmin@123",
                            Username = "superadmin"
                        },
                        new
                        {
                            Id = 2L,
                            IsActive = true,
                            Password = "supervisor@123",
                            Username = "supervisor"
                        },
                        new
                        {
                            Id = 3L,
                            IsActive = true,
                            Password = "kishore@123",
                            Username = "Kishore"
                        },
                        new
                        {
                            Id = 4L,
                            IsActive = true,
                            Password = "satheesh@123",
                            Username = "Satheesh"
                        });
                });

            modelBuilder.Entity("AutoSync.Core.Authorization.UserRoles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AuditDetailId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            RoleId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            RoleId = 3L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            RoleId = 5L,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            RoleId = 5L,
                            UserId = 4L
                        });
                });

            modelBuilder.Entity("AutoSync.Core.Job.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DestinationFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyncType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalFileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("AutoSync.Core.Job.JobDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseFolderPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<string>("S3FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
